#!/bin/bash
# vim: set expandtab tabstop=4 shiftwidth=4 textwidth=79 foldmethod=marker:
# GPL {{{1
#############################################################################
# Copyright 2012 Ivan F. Villanueva B. <ivan ät gridmind.org>
#
# This file is part of GridCalendar.
#
# GridCalendar is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# GridCalendar is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the Affero GNU General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License
# along with GridCalendar. If not, see <http://www.gnu.org/licenses/>.
#############################################################################

# DOC {{{1
# This script performs several automations after gridcalendar repository is
# updated (after push). It is intended to be run by a mercurial changegroup
# hook.
# 1) generates docs
# 2) updates the working copy

# BODY {{{1
set -e # same as putting '|| exit 1' everywhere

DOC_DEST=$HG_NODE/docs/html

# Update.
cd $HG_NODE
hg update

# Get the documentation source from $HG_NODE/docs, build
# it, and put the result in $DOC_DEST.
TMPDIR=`mktemp -d`
cp -R $HG_NODE/docs $TMPDIR/
cd $TMPDIR/docs
make SPHINXOPTS=-q html
cp -R _build/html/* $DOC_DEST/
chmod -R g+w $DOC_DEST >/dev/null 2>&1
rm -rf $TMPDIR
