if has('autocmd')
  filetype plugin indent on
endif
if has('syntax') && !exists('g:syntax_on')
  syntax enable
endif

" ****************************************************************************
" settings
" ****************************************************************************

set nocompatible	" Use Vim defaults instead of 100% vi compatibility

" switching to the existing tab if the buffer is open, or creating a new one if not
set switchbuf=usetab,newtab
" When opening a file, keep the old one open
set hidden

" WARNING: security issue
set modeline

set encoding=UTF-8
set fileencodings="ucs-bom,latin1,iso-8859-1,iso-8859-15,utf-8"

" http://vim.wikia.com/wiki/Fix_syntax_highlighting
syntax sync fromstart
autocmd BufEnter * :syntax sync fromstart

set t_Co=256

:set wildignore+=*.o,*.obj,.git,.hg,*.pyc

set ruler		" show the cursor position all the time
set showcmd		" Show (partial) command in status line.
set showmatch	" Show matching brackets.

set colorcolumn=+1
set linebreak

set shiftround
set autoindent                  " Copy indent from current line when starting a new line 
set expandtab
set tabstop=4
set shiftwidth=4
set backspace=indent,eol,start
set ignorecase smartcase " Do case insensitive matching when the pattern is lowercase

set ttimeout
set ttimeoutlen=100

set iskeyword+=-

set smartcase
set incsearch
set hlsearch " highlight all search matches,
" Use <C-n> to clear the highlighting:
map <C-n> :nohlsearch<CR>

" Show match when a clossing bracket is inserted
set sm

if &history < 1000
  set history=1000
endif
if &tabpagemax < 50
  set tabpagemax=50
endif

if !empty(&viminfo)
    " read/write a .viminfo file, don't store more than 50 lines of registers
    set viminfo='20,\"50
endif

" Suffixes that get lower priority when doing tab completion for filenames.
" These are files we are not likely to want to edit or read.
set suffixes=.bak,~,.swp,.o,.info,.aux,.log,.dvi,.bbl,.blg,.brf,.cb,.ind,.idx,.ilg,.inx,.out,.toc,.class,.pyc

set nrformats-=octal

set backup                      " Keep a backup
set backupdir=~/.vim/backups    " Set dir to save backups files (they end in ~)

" see help gui-x11-misc
set clipboard=exclude:cons\|linux

" grep will sometimes skip displaying the file name if you
" search in a singe file. This will confuse Latex-Suite. Set your grep
" program to alway generate a file-name.
set grepprg=grep\ -nH\ $*
